destroy update

diff --git a/.github/workflows/github-action-cicd.yml b/.github/workflows/github-action-cicd.yml
--- a/.github/workflows/github-action-cicd.yml
+++ b/.github/workflows/github-action-cicd.yml
@@ -165,52 +165,52 @@ jobs:
 
 
         
-destroy:
-  needs: deploy
-  if: >
-    github.event_name == 'pull_request' &&
-    github.head_ref == 'test-deploy' &&
-    success()
+  destroy:
+    needs: deploy
+    if: >
+      github.event_name == 'pull_request' &&
+      github.head_ref == 'test-deploy' &&
+      success()
 
-  runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
 
-  steps:
-    - name: Checkout current repo
-      uses: actions/checkout@v4
+    steps:
+      - name: Checkout current repo
+        uses: actions/checkout@v4
 
-    # Authenticate to Google Cloud via WIF
-    - name: Authenticate to Google Cloud
-      uses: google-github-actions/auth@v2
-      with:
-        workload_identity_provider: "projects/696820564091/locations/global/workloadIdentityPools/github-pool-v2/providers/github-v2"
-        service_account: "github-action@curamet-onboarding.iam.gserviceaccount.com"
+      # Authenticate to Google Cloud via WIF
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2
+        with:
+          workload_identity_provider: "projects/696820564091/locations/global/workloadIdentityPools/github-pool-v2/providers/github-v2"
+          service_account: "github-action@curamet-onboarding.iam.gserviceaccount.com"
 
-    # Setup gcloud
-    - name: Setup gcloud
-      uses: google-github-actions/setup-gcloud@v2
-      with:
-        project_id: curamet-onboarding
-
-
-    # cleanup GCP resources like deploy job cleanup
-    - name: Cleanup GCP resources (optional)
-      run: |
-        gcloud artifacts repositories delete vv-curamet-repo --location=europe --quiet || true
-        gcloud artifacts repositories delete vv-curamet-repo --location=europe-west1 --quiet || true
-        gcloud iam service-accounts delete vv-sa-demo-service-runner@curamet-onboarding.iam.gserviceaccount.com --quiet || true
-        gcloud iam service-accounts delete vv-sa-demo-service-invoker@curamet-onboarding.iam.gserviceaccount.com --quiet || true
-        gcloud secrets delete vv-demo-secret --quiet || true
-        gcloud storage rm --recursive gs://vv-curamet-bucket || true
-        gcloud pubsub topics delete vv-dead-letter-topic --quiet || true
-        gcloud pubsub topics delete vv-demo-topic --quiet || true
-        gcloud pubsub topics delete vv-object-notification-topic --quiet || true
-        gcloud pubsub subscriptions delete vv-dead-lettering-subscription --quiet || true
-        gcloud pubsub subscriptions delete vv-subscription-trigger-demo-service --quiet || true
-        gcloud pubsub subscriptions delete vv-subscription-object-notification --quiet || true
-        gcloud run services delete vv-demo-service-v2 --region=europe-west1 --quiet || true
+      # Setup gcloud
+      - name: Setup gcloud
+        uses: google-github-actions/setup-gcloud@v2
+        with:
+          project_id: curamet-onboarding
 
 
-    # Terraform Destroy (final cleanup)
-    - name: Terraform Destroy
-      working-directory: terraform
-      run: terraform destroy -var-file="environments/dev/terraform.tfvars" -auto-approve
+      # cleanup GCP resources like deploy job cleanup
+      - name: Cleanup GCP resources (optional)
+        run: |
+          gcloud artifacts repositories delete vv-curamet-repo --location=europe --quiet || true
+          gcloud artifacts repositories delete vv-curamet-repo --location=europe-west1 --quiet || true
+          gcloud iam service-accounts delete vv-sa-demo-service-runner@curamet-onboarding.iam.gserviceaccount.com --quiet || true
+          gcloud iam service-accounts delete vv-sa-demo-service-invoker@curamet-onboarding.iam.gserviceaccount.com --quiet || true
+          gcloud secrets delete vv-demo-secret --quiet || true
+          gcloud storage rm --recursive gs://vv-curamet-bucket || true
+          gcloud pubsub topics delete vv-dead-letter-topic --quiet || true
+          gcloud pubsub topics delete vv-demo-topic --quiet || true
+          gcloud pubsub topics delete vv-object-notification-topic --quiet || true
+          gcloud pubsub subscriptions delete vv-dead-lettering-subscription --quiet || true
+          gcloud pubsub subscriptions delete vv-subscription-trigger-demo-service --quiet || true
+          gcloud pubsub subscriptions delete vv-subscription-object-notification --quiet || true
+          gcloud run services delete vv-demo-service-v2 --region=europe-west1 --quiet || true
+
+
+      # Terraform Destroy (final cleanup)
+      - name: Terraform Destroy
+        working-directory: terraform
+        run: terraform destroy -var-file="environments/dev/terraform.tfvars" -auto-approve
